// import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="m-7 text-xl">
        Contact Page Mein Apka Swagat Hai   
        {children}
      </body>
    </html>
  );
}
